# ShoutAll v2.0
# by CowNow
# ============================== #
# 变量列表:
# <permission> - LuckPerms使用的权限组
# <sec> - 默认冷却时间
# <msec> - 跳过的冷却时间
# <prefix> - 玩家前缀 (如果有)
# <player> - 玩家名
# <server> - 本配置中的服务器名
# <bungee> - BungeeCord配置文件中的服务器名
# ============================== #

# 对于不同权限组的冷却时间
# # 这个只是一个例子，你可以自己更改它
cooldown:
  none: 180
  vip: 90
  vip_plus: 60
  mvp: 30
  mvp_plus: 10

# 提示文本
Message:
  Cooldown: "&c你还需要等待<sec>秒才能使用喊话。"
  CooldownBypass: "&a你拥有<permission>权限，节省了<msec>秒."
  PlayerOnly: "&c该命令只能由玩家执行！"
  ReloadSuccess: "配置已重载"
  WrongArg: "&c参数错误。"
  InvalidServer: "&c执行喊话时出错！请检查玩家&e<player>&c所在的服务器&e<bungee>是否加入配置列表中？"
  ShoutFailed: "&c你所在的服务器无法使用喊话，请向管理员报告这个问题。"
  TokenOutdated: "&cToken无效或已过期！"

# 喊话格式1: /hh
# 效果:
# ➤ [Admin]CowNow 邀请你游玩起床战争！ 点击加入！
ShoutFormat-1:
  # 格式
  ShoutMessage: "&b➤ <prefix><player> &b邀请你加入&e&l<server>！"
  # 按钮标题
  ClickMessage: "&6&l点击加入！"
  # 按钮悬浮文本
  HoverMessage: "&6&n点击加入！"
  Footer: "&b to join!"

# 喊话格式2: /hh + <喊话内容>
# 效果：
# [全服喊话] [Admin]CowNow: 远控为您注入Vape (点击传送)
ShoutFormat-2:
  # 喊话前缀
  ShoutPrefix: "&6[全服喊话] "
  # 按钮标题
  ClickMessage: "&b&l&n(Click to Teleport)"
  # 按钮悬浮文本
  HoverMessage: "&bTeleport to the &e<server> server"

# Server list
# The Variable named <server> will be use the server name you set.
# This list is an example, you can change it yourself.
server:
  Lobby#1: Lobby1
  Lobby#2: Lobby2
  bw-4v4-1: Bedwars-4v4
  bw-4v4-2: Bedwars-4v4
  bw-solo-1: Bedwars-solo
  bw-solo-2: Bedwars-solo
  RushBed: RushBed
  Bridge: Bridge
  MegaWall-1: MegaWall
  MegaWall-2: MegaWall
  zombies-aa-1: Zombies
  zombies-bb-2: Zombies
  zombies-de-3: Zombies
  CSGO: Csgo
  BattleRoyal: BattleRoyal
  ThePit: ThePit